; Dataform block keywords
"config" @keyword
"js" @keyword
"pre_operations" @keyword
"post_operations" @keyword

; Basic tokens
(comment) @comment
(string) @string
(number) @number
(symbol) @operator

; Interpolations
(interpolation
  "${" @punctuation.special
  "}" @punctuation.special) @embedded

; BigQuery SQL keywords
((identifier) @keyword
 (#match? @keyword "^(?i)(SELECT|FROM|WHERE|GROUP|BY|ORDER|LIMIT|OFFSET|HAVING|AS|JOIN|ON|LEFT|RIGHT|INNER|OUTER|FULL|CROSS|UNION|INTERSECT|EXCEPT|ALL|DISTINCT|CASE|WHEN|THEN|ELSE|END|AND|OR|NOT|IN|IS|NULL|TRUE|FALSE|BETWEEN|LIKE|EXISTS|ASC|DESC|NULLS|FIRST|LAST|OVER|PARTITION|WINDOW|ROWS|RANGE|UNBOUNDED|PRECEDING|FOLLOWING|CURRENT|ROW|WITH|RECURSIVE|CREATE|REPLACE|VIEW|TABLE|TEMP|TEMPORARY|MATERIALIZED|IF|INSERT|INTO|VALUES|UPDATE|SET|DELETE|TRUNCATE|MERGE|USING|MATCHED|DROP|ALTER|ADD|COLUMN|RENAME|TO|GRANT|REVOKE|DECLARE|DEFAULT|BEGIN|TRANSACTION|COMMIT|ROLLBACK|FOR|LOOP|WHILE|BREAK|CONTINUE|RETURN|CALL|EXPORT|IMPORT|OPTIONS|CLUSTER|ASSERT|QUALIFY|PIVOT|UNPIVOT|TABLESAMPLE|PERCENT|SYSTEM|LATERAL|NATURAL|SEMI|ANTI|RESPECT|IGNORE)$"))

; BigQuery types
((identifier) @type
 (#match? @type "^(?i)(INT64|INT|SMALLINT|INTEGER|BIGINT|TINYINT|BYTEINT|FLOAT64|FLOAT|NUMERIC|BIGNUMERIC|DECIMAL|BIGDECIMAL|BOOL|BOOLEAN|STRING|BYTES|DATE|DATETIME|TIME|TIMESTAMP|INTERVAL|GEOGRAPHY|JSON|ARRAY|STRUCT|RANGE|ANY|TYPE)$"))

; BigQuery built-in functions - aggregate
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(COUNT|SUM|AVG|MIN|MAX|ANY_VALUE|ARRAY_AGG|ARRAY_CONCAT_AGG|BIT_AND|BIT_OR|BIT_XOR|COUNTIF|LOGICAL_AND|LOGICAL_OR|STRING_AGG|APPROX_COUNT_DISTINCT|APPROX_QUANTILES|APPROX_TOP_COUNT|APPROX_TOP_SUM|HLL_COUNT_INIT|HLL_COUNT_MERGE|HLL_COUNT_MERGE_PARTIAL|HLL_COUNT_EXTRACT|CORR|COVAR_POP|COVAR_SAMP|STDDEV|STDDEV_POP|STDDEV_SAMP|VAR_POP|VAR_SAMP|VARIANCE)$"))

; BigQuery built-in functions - window/analytic
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(ROW_NUMBER|RANK|DENSE_RANK|PERCENT_RANK|CUME_DIST|NTILE|LEAD|LAG|FIRST_VALUE|LAST_VALUE|NTH_VALUE|PERCENTILE_CONT|PERCENTILE_DISC)$"))

; BigQuery built-in functions - string
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(ASCII|BYTE_LENGTH|CHAR_LENGTH|CHARACTER_LENGTH|CHR|CODE_POINTS_TO_BYTES|CODE_POINTS_TO_STRING|COLLATE|CONCAT|CONTAINS_SUBSTR|EDIT_DISTANCE|ENDS_WITH|FORMAT|FROM_BASE32|FROM_BASE64|FROM_HEX|INITCAP|INSTR|LEFT|LENGTH|LOWER|LPAD|LTRIM|NORMALIZE|NORMALIZE_AND_CASEFOLD|OCTET_LENGTH|REGEXP_CONTAINS|REGEXP_EXTRACT|REGEXP_EXTRACT_ALL|REGEXP_INSTR|REGEXP_REPLACE|REGEXP_SUBSTR|REPEAT|REPLACE|REVERSE|RIGHT|RPAD|RTRIM|SAFE_CONVERT_BYTES_TO_STRING|SOUNDEX|SPLIT|STARTS_WITH|STRPOS|SUBSTR|SUBSTRING|TO_BASE32|TO_BASE64|TO_CODE_POINTS|TO_HEX|TRANSLATE|TRIM|UNICODE|UPPER)$"))

; BigQuery built-in functions - math
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(ABS|ACOS|ACOSH|ASIN|ASINH|ATAN|ATAN2|ATANH|CBRT|CEIL|CEILING|COS|COSH|COT|COTH|CSC|CSCH|DIV|EXP|FLOOR|GREATEST|IEEE_DIVIDE|IS_INF|IS_NAN|LEAST|LN|LOG|LOG10|MOD|PI|POW|POWER|RAND|RANDOM|RANGE_BUCKET|ROUND|SAFE_ADD|SAFE_DIVIDE|SAFE_MULTIPLY|SAFE_NEGATE|SAFE_SUBTRACT|SEC|SECH|SIGN|SIN|SINH|SQRT|TAN|TANH|TRUNC)$"))

; BigQuery built-in functions - date/time
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(CURRENT_DATE|CURRENT_DATETIME|CURRENT_TIME|CURRENT_TIMESTAMP|DATE|DATETIME|TIME|TIMESTAMP|DATE_ADD|DATE_SUB|DATE_DIFF|DATE_TRUNC|DATE_FROM_UNIX_DATE|DATETIME_ADD|DATETIME_SUB|DATETIME_DIFF|DATETIME_TRUNC|TIME_ADD|TIME_SUB|TIME_DIFF|TIME_TRUNC|TIMESTAMP_ADD|TIMESTAMP_SUB|TIMESTAMP_DIFF|TIMESTAMP_TRUNC|TIMESTAMP_SECONDS|TIMESTAMP_MILLIS|TIMESTAMP_MICROS|UNIX_DATE|UNIX_SECONDS|UNIX_MILLIS|UNIX_MICROS|EXTRACT|FORMAT_DATE|FORMAT_DATETIME|FORMAT_TIME|FORMAT_TIMESTAMP|PARSE_DATE|PARSE_DATETIME|PARSE_TIME|PARSE_TIMESTAMP|LAST_DAY|GENERATE_DATE_ARRAY|GENERATE_TIMESTAMP_ARRAY)$"))

; BigQuery built-in functions - conversion/casting
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(CAST|SAFE_CAST|PARSE_BIGNUMERIC|PARSE_NUMERIC|TO_JSON|TO_JSON_STRING|PARSE_JSON|JSON_EXTRACT|JSON_EXTRACT_SCALAR|JSON_EXTRACT_ARRAY|JSON_EXTRACT_STRING_ARRAY|JSON_QUERY|JSON_QUERY_ARRAY|JSON_VALUE|JSON_VALUE_ARRAY|JSON_TYPE|LAX_BOOL|LAX_FLOAT64|LAX_INT64|LAX_STRING|INT64|FLOAT64|BOOL|STRING)$"))

; BigQuery built-in functions - array
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(ARRAY|ARRAY_CONCAT|ARRAY_LENGTH|ARRAY_REVERSE|ARRAY_TO_STRING|GENERATE_ARRAY|ARRAY_FILTER|ARRAY_TRANSFORM|ARRAY_INCLUDES|ARRAY_INCLUDES_ANY|ARRAY_INCLUDES_ALL|FLATTEN)$"))

; BigQuery built-in functions - struct/geography/other
((identifier) @function.builtin
 (#match? @function.builtin "^(?i)(STRUCT|ST_GEOGPOINT|ST_MAKELINE|ST_MAKEPOLYGON|ST_GEOGFROMTEXT|ST_GEOGFROMGEOJSON|ST_ASTEXT|ST_ASGEOJSON|ST_DISTANCE|ST_AREA|ST_LENGTH|ST_PERIMETER|ST_CONTAINS|ST_INTERSECTS|ST_WITHIN|ST_COVERS|ST_COVEREDBY|ST_UNION|ST_INTERSECTION|ST_DIFFERENCE|ST_BUFFER|ST_CENTROID|ST_CLOSESTPOINT|ST_BOUNDARY|ST_X|ST_Y|COALESCE|IFNULL|NULLIF|NVL|IF|IIF|HASH|FARM_FINGERPRINT|MD5|SHA1|SHA256|SHA512|ERROR|GENERATE_UUID|SESSION_USER|NET_HOST|NET_PUBLIC_SUFFIX|NET_REG_DOMAIN|NET_IP_FROM_STRING|NET_IP_TO_STRING|NET_IP_NET_MASK|NET_IP_TRUNC|NET_IPV4_FROM_INT64|NET_IPV4_TO_INT64|NET_SAFE_IP_FROM_STRING)$"))
