/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 96
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 1
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_config = 1,
  anon_sym_js = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  aux_sym__js_content_raw_token1 = 5,
  anon_sym_pre_operations = 6,
  anon_sym_post_operations = 7,
  aux_sym__braced_code_token1 = 8,
  sym_identifier = 9,
  sym_number = 10,
  sym_symbol = 11,
  anon_sym_DOLLAR_LBRACE = 12,
  aux_sym_interpolation_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_string_token1 = 15,
  anon_sym_BSLASH = 16,
  aux_sym_string_token2 = 17,
  anon_sym_SQUOTE = 18,
  aux_sym_string_token3 = 19,
  anon_sym_BQUOTE = 20,
  aux_sym_string_token4 = 21,
  sym_comment = 22,
  sym_source_file = 23,
  sym_config_block = 24,
  sym_js_block = 25,
  sym_js_content = 26,
  aux_sym__js_content_raw = 27,
  sym__js_braced = 28,
  sym_pre_operations_block = 29,
  sym_post_operations_block = 30,
  sym__braced_code = 31,
  sym_statement = 32,
  sym_interpolation = 33,
  sym_string = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym__js_braced_repeat1 = 36,
  aux_sym_pre_operations_block_repeat1 = 37,
  aux_sym__braced_code_repeat1 = 38,
  aux_sym_interpolation_repeat1 = 39,
  aux_sym_string_repeat1 = 40,
  aux_sym_string_repeat2 = 41,
  aux_sym_string_repeat3 = 42,
  anon_alias_sym_js_content = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_config] = "config",
  [anon_sym_js] = "js",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__js_content_raw_token1] = "_js_content_raw_token1",
  [anon_sym_pre_operations] = "pre_operations",
  [anon_sym_post_operations] = "post_operations",
  [aux_sym__braced_code_token1] = "_braced_code_token1",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_symbol] = "symbol",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_interpolation_token1] = "interpolation_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token3] = "string_token3",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_token4] = "string_token4",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_config_block] = "config_block",
  [sym_js_block] = "js_block",
  [sym_js_content] = "js_content",
  [aux_sym__js_content_raw] = "_js_content_raw",
  [sym__js_braced] = "_js_braced",
  [sym_pre_operations_block] = "pre_operations_block",
  [sym_post_operations_block] = "post_operations_block",
  [sym__braced_code] = "_braced_code",
  [sym_statement] = "statement",
  [sym_interpolation] = "interpolation",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__js_braced_repeat1] = "_js_braced_repeat1",
  [aux_sym_pre_operations_block_repeat1] = "pre_operations_block_repeat1",
  [aux_sym__braced_code_repeat1] = "_braced_code_repeat1",
  [aux_sym_interpolation_repeat1] = "interpolation_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_string_repeat3] = "string_repeat3",
  [anon_alias_sym_js_content] = "js_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_js] = anon_sym_js,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__js_content_raw_token1] = aux_sym__js_content_raw_token1,
  [anon_sym_pre_operations] = anon_sym_pre_operations,
  [anon_sym_post_operations] = anon_sym_post_operations,
  [aux_sym__braced_code_token1] = aux_sym__braced_code_token1,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_symbol] = sym_symbol,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_interpolation_token1] = aux_sym_interpolation_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_token4] = aux_sym_string_token4,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_config_block] = sym_config_block,
  [sym_js_block] = sym_js_block,
  [sym_js_content] = sym_js_content,
  [aux_sym__js_content_raw] = aux_sym__js_content_raw,
  [sym__js_braced] = sym__js_braced,
  [sym_pre_operations_block] = sym_pre_operations_block,
  [sym_post_operations_block] = sym_post_operations_block,
  [sym__braced_code] = sym__braced_code,
  [sym_statement] = sym_statement,
  [sym_interpolation] = sym_interpolation,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__js_braced_repeat1] = aux_sym__js_braced_repeat1,
  [aux_sym_pre_operations_block_repeat1] = aux_sym_pre_operations_block_repeat1,
  [aux_sym__braced_code_repeat1] = aux_sym__braced_code_repeat1,
  [aux_sym_interpolation_repeat1] = aux_sym_interpolation_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_string_repeat3] = aux_sym_string_repeat3,
  [anon_alias_sym_js_content] = anon_alias_sym_js_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_js] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__js_content_raw_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_pre_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post_operations] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__braced_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_config_block] = {
    .visible = true,
    .named = true,
  },
  [sym_js_block] = {
    .visible = true,
    .named = true,
  },
  [sym_js_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__js_content_raw] = {
    .visible = false,
    .named = false,
  },
  [sym__js_braced] = {
    .visible = false,
    .named = true,
  },
  [sym_pre_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_post_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym__braced_code] = {
    .visible = false,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__js_braced_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pre_operations_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__braced_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat3] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_js_content] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_js_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__js_content_raw, 2,
    aux_sym__js_content_raw,
    anon_alias_sym_js_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 23,
  [32] = 28,
  [33] = 24,
  [34] = 28,
  [35] = 4,
  [36] = 8,
  [37] = 9,
  [38] = 16,
  [39] = 17,
  [40] = 40,
  [41] = 9,
  [42] = 18,
  [43] = 9,
  [44] = 18,
  [45] = 17,
  [46] = 17,
  [47] = 10,
  [48] = 10,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 57,
  [62] = 54,
  [63] = 54,
  [64] = 64,
  [65] = 65,
  [66] = 55,
  [67] = 55,
  [68] = 57,
  [69] = 54,
  [70] = 56,
  [71] = 64,
  [72] = 65,
  [73] = 55,
  [74] = 64,
  [75] = 57,
  [76] = 65,
  [77] = 56,
  [78] = 64,
  [79] = 65,
  [80] = 56,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '"', 80,
        '$', 11,
        '\'', 90,
        '-', 71,
        '/', 70,
        '\\', 85,
        '`', 95,
        'c', 49,
        'j', 59,
        'p', 51,
        '{', 16,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (lookahead == '!' ||
          ('(' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '>') ||
          ('[' <= lookahead && lookahead <= ']')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '-') ADVANCE(88);
      if (lookahead == '/') ADVANCE(87);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '$') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(90);
      if (lookahead == '-') ADVANCE(71);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead == '`') ADVANCE(95);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      if (lookahead == '!' ||
          ('(' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '>') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(90);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead == '`') ADVANCE(95);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0) ADVANCE(79);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '\'') ADVANCE(90);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead == '`') ADVANCE(95);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(33);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead == '/') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(90);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead == '/') ADVANCE(92);
      if (lookahead == '\\') ADVANCE(85);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(100);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(19);
      if (lookahead == '{') ADVANCE(16);
      if (lookahead == '}') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(98);
      if (lookahead == '/') ADVANCE(97);
      if (lookahead == '\\') ADVANCE(85);
      if (lookahead == '`') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 11:
      if (lookahead == '{') ADVANCE(72);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_config);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_js);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '\n') ADVANCE(24);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(101);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '-') ADVANCE(23);
      if (lookahead == '/') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_post_operations);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(101);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '/') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '/') ADVANCE(33);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '*') ADVANCE(29);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead == '/') ADVANCE(28);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__braced_code_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(60);
      if (lookahead == 'r') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_symbol);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '\n') ADVANCE(79);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(101);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(76);
      if (lookahead == '/') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(75);
      if (lookahead == '/') ADVANCE(79);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(75);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(8);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '-') ADVANCE(78);
      if (lookahead == '/') ADVANCE(74);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '-') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead == '/') ADVANCE(82);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(81);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(88);
      if (lookahead == '/') ADVANCE(87);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(86);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_string_token3);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead == '/') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(91);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_string_token4);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(101);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '-') ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '-') ADVANCE(98);
      if (lookahead == '/') ADVANCE(97);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(96);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(101);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 4},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 9},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 9},
  [50] = {.lex_state = 9},
  [51] = {.lex_state = 9},
  [52] = {.lex_state = 9},
  [53] = {.lex_state = 9},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 10},
  [57] = {.lex_state = 5},
  [58] = {.lex_state = 5},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 10},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 6},
  [63] = {.lex_state = 6},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 10},
  [67] = {.lex_state = 10},
  [68] = {.lex_state = 5},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 10},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 6},
  [73] = {.lex_state = 10},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 10},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 6},
  [80] = {.lex_state = 10},
  [81] = {.lex_state = 6},
  [82] = {.lex_state = 9},
  [83] = {.lex_state = 9},
  [84] = {.lex_state = 5},
  [85] = {.lex_state = 9},
  [86] = {.lex_state = 10},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_js] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pre_operations] = ACTIONS(1),
    [anon_sym_post_operations] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(92),
    [sym_config_block] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_pre_operations_block] = STATE(2),
    [sym_post_operations_block] = STATE(2),
    [sym_statement] = STATE(2),
    [sym_interpolation] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_config] = ACTIONS(7),
    [anon_sym_js] = ACTIONS(9),
    [anon_sym_pre_operations] = ACTIONS(11),
    [anon_sym_post_operations] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_symbol] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_config,
    ACTIONS(9), 1,
      anon_sym_js,
    ACTIONS(11), 1,
      anon_sym_pre_operations,
    ACTIONS(13), 1,
      anon_sym_post_operations,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      anon_sym_BQUOTE,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      sym_identifier,
      sym_symbol,
    STATE(4), 2,
      sym_interpolation,
      sym_string,
    STATE(3), 6,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_statement,
      aux_sym_source_file_repeat1,
  [50] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_config,
    ACTIONS(34), 1,
      anon_sym_js,
    ACTIONS(37), 1,
      anon_sym_pre_operations,
    ACTIONS(40), 1,
      anon_sym_post_operations,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(49), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(43), 2,
      sym_identifier,
      sym_symbol,
    STATE(4), 2,
      sym_interpolation,
      sym_string,
    STATE(3), 6,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_statement,
      aux_sym_source_file_repeat1,
  [100] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(63), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(67), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [140] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(75), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(13), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(35), 2,
      sym_interpolation,
      sym_string,
  [174] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(75), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(15), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(35), 2,
      sym_interpolation,
      sym_string,
  [208] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(87), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [228] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(91), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(95), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [268] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(99), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(103), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [308] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(75), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(21), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(35), 2,
      sym_interpolation,
      sym_string,
  [342] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(109), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [362] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_symbol,
    ACTIONS(75), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(77), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_SQUOTE,
    ACTIONS(81), 1,
      anon_sym_BQUOTE,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    ACTIONS(71), 2,
      sym_identifier,
      sym_number,
    STATE(21), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(35), 2,
      sym_interpolation,
      sym_string,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(115), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(119), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(123), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(127), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [476] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(131), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [496] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(138), 1,
      sym_symbol,
    ACTIONS(141), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(147), 1,
      anon_sym_SQUOTE,
    ACTIONS(150), 1,
      anon_sym_BQUOTE,
    ACTIONS(135), 2,
      sym_identifier,
      sym_number,
    STATE(21), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(35), 2,
      sym_interpolation,
      sym_string,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(155), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [550] = 7,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_BQUOTE,
    ACTIONS(161), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(26), 3,
      sym__braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [575] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(173), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(29), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [600] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(29), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [625] = 7,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_BQUOTE,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(27), 3,
      sym__braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [650] = 7,
    ACTIONS(187), 1,
      anon_sym_LBRACE,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 1,
      anon_sym_DQUOTE,
    ACTIONS(198), 1,
      anon_sym_SQUOTE,
    ACTIONS(201), 1,
      anon_sym_BQUOTE,
    ACTIONS(192), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(27), 3,
      sym__braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [675] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(204), 1,
      anon_sym_RBRACE,
    ACTIONS(206), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(25), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [700] = 7,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(211), 1,
      anon_sym_RBRACE,
    ACTIONS(216), 1,
      anon_sym_DQUOTE,
    ACTIONS(219), 1,
      anon_sym_SQUOTE,
    ACTIONS(222), 1,
      anon_sym_BQUOTE,
    ACTIONS(213), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(29), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [725] = 7,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_BQUOTE,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(185), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(27), 3,
      sym__braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [750] = 7,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_DQUOTE,
    ACTIONS(165), 1,
      anon_sym_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_BQUOTE,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(229), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(30), 3,
      sym__braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [775] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(231), 1,
      anon_sym_RBRACE,
    ACTIONS(233), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(33), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [800] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(235), 1,
      anon_sym_RBRACE,
    ACTIONS(173), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(29), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [825] = 7,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_DQUOTE,
    ACTIONS(177), 1,
      anon_sym_SQUOTE,
    ACTIONS(179), 1,
      anon_sym_BQUOTE,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    ACTIONS(239), 2,
      aux_sym__braced_code_token1,
      sym_comment,
    STATE(24), 3,
      sym__braced_code,
      sym_string,
      aux_sym__braced_code_repeat1,
  [850] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      sym_symbol,
    ACTIONS(61), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [866] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      sym_symbol,
    ACTIONS(85), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [882] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      sym_symbol,
    ACTIONS(89), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [898] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_symbol,
    ACTIONS(113), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [914] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      sym_symbol,
    ACTIONS(117), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [930] = 7,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(243), 1,
      anon_sym_RBRACE,
    ACTIONS(245), 1,
      aux_sym__js_content_raw_token1,
    ACTIONS(247), 1,
      sym_comment,
    STATE(52), 1,
      aux_sym__js_content_raw,
    STATE(82), 1,
      sym__js_braced,
    STATE(90), 1,
      sym_js_content,
  [952] = 1,
    ACTIONS(91), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [962] = 1,
    ACTIONS(123), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [972] = 1,
    ACTIONS(91), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__braced_code_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [982] = 1,
    ACTIONS(123), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__braced_code_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [992] = 1,
    ACTIONS(119), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1002] = 1,
    ACTIONS(119), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__braced_code_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1012] = 1,
    ACTIONS(95), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__braced_code_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1022] = 1,
    ACTIONS(95), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1032] = 5,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_RBRACE,
    ACTIONS(251), 1,
      aux_sym__js_content_raw_token1,
    STATE(50), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1049] = 5,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_RBRACE,
    ACTIONS(255), 1,
      aux_sym__js_content_raw_token1,
    STATE(53), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1066] = 6,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LBRACE,
    ACTIONS(260), 1,
      anon_sym_RBRACE,
    ACTIONS(262), 1,
      aux_sym__js_content_raw_token1,
    STATE(51), 1,
      aux_sym__js_content_raw,
    STATE(82), 1,
      sym__js_braced,
  [1085] = 6,
    ACTIONS(241), 1,
      anon_sym_LBRACE,
    ACTIONS(245), 1,
      aux_sym__js_content_raw_token1,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
    STATE(51), 1,
      aux_sym__js_content_raw,
    STATE(82), 1,
      sym__js_braced,
  [1104] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_LBRACE,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    ACTIONS(272), 1,
      aux_sym__js_content_raw_token1,
    STATE(53), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1121] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(277), 1,
      anon_sym_SQUOTE,
    ACTIONS(279), 1,
      aux_sym_string_token3,
    STATE(79), 1,
      aux_sym_string_repeat2,
  [1137] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(283), 1,
      anon_sym_BQUOTE,
    ACTIONS(285), 1,
      aux_sym_string_token4,
    STATE(60), 1,
      aux_sym_string_repeat3,
  [1153] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(287), 1,
      anon_sym_BQUOTE,
    ACTIONS(289), 1,
      aux_sym_string_token4,
    STATE(67), 1,
      aux_sym_string_repeat3,
  [1169] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_DQUOTE,
    ACTIONS(291), 1,
      aux_sym_string_token1,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    STATE(74), 1,
      aux_sym_string_repeat1,
  [1185] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(295), 1,
      anon_sym_DQUOTE,
    ACTIONS(297), 1,
      aux_sym_string_token1,
    ACTIONS(300), 1,
      anon_sym_BSLASH,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [1201] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_BSLASH,
    ACTIONS(306), 1,
      anon_sym_SQUOTE,
    ACTIONS(308), 1,
      aux_sym_string_token3,
    STATE(59), 1,
      aux_sym_string_repeat2,
  [1217] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(314), 1,
      anon_sym_BQUOTE,
    ACTIONS(316), 1,
      aux_sym_string_token4,
    STATE(60), 1,
      aux_sym_string_repeat3,
  [1233] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(319), 1,
      anon_sym_DQUOTE,
    ACTIONS(321), 1,
      aux_sym_string_token1,
    STATE(64), 1,
      aux_sym_string_repeat1,
  [1249] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(319), 1,
      anon_sym_SQUOTE,
    ACTIONS(323), 1,
      aux_sym_string_token3,
    STATE(65), 1,
      aux_sym_string_repeat2,
  [1265] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(287), 1,
      anon_sym_SQUOTE,
    ACTIONS(325), 1,
      aux_sym_string_token3,
    STATE(76), 1,
      aux_sym_string_repeat2,
  [1281] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(327), 1,
      anon_sym_DQUOTE,
    ACTIONS(329), 1,
      aux_sym_string_token1,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [1297] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(327), 1,
      anon_sym_SQUOTE,
    ACTIONS(331), 1,
      aux_sym_string_token3,
    STATE(59), 1,
      aux_sym_string_repeat2,
  [1313] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(285), 1,
      aux_sym_string_token4,
    ACTIONS(327), 1,
      anon_sym_BQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat3,
  [1329] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(285), 1,
      aux_sym_string_token4,
    ACTIONS(333), 1,
      anon_sym_BQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat3,
  [1345] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(335), 1,
      anon_sym_DQUOTE,
    ACTIONS(337), 1,
      aux_sym_string_token1,
    STATE(71), 1,
      aux_sym_string_repeat1,
  [1361] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(335), 1,
      anon_sym_SQUOTE,
    ACTIONS(339), 1,
      aux_sym_string_token3,
    STATE(72), 1,
      aux_sym_string_repeat2,
  [1377] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(335), 1,
      anon_sym_BQUOTE,
    ACTIONS(341), 1,
      aux_sym_string_token4,
    STATE(73), 1,
      aux_sym_string_repeat3,
  [1393] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(329), 1,
      aux_sym_string_token1,
    ACTIONS(343), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [1409] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(331), 1,
      aux_sym_string_token3,
    ACTIONS(343), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      aux_sym_string_repeat2,
  [1425] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(285), 1,
      aux_sym_string_token4,
    ACTIONS(343), 1,
      anon_sym_BQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat3,
  [1441] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(329), 1,
      aux_sym_string_token1,
    ACTIONS(333), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [1457] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_DQUOTE,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(345), 1,
      aux_sym_string_token1,
    STATE(78), 1,
      aux_sym_string_repeat1,
  [1473] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(331), 1,
      aux_sym_string_token3,
    ACTIONS(333), 1,
      anon_sym_SQUOTE,
    STATE(59), 1,
      aux_sym_string_repeat2,
  [1489] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_BQUOTE,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(347), 1,
      aux_sym_string_token4,
    STATE(55), 1,
      aux_sym_string_repeat3,
  [1505] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_DQUOTE,
    ACTIONS(293), 1,
      anon_sym_BSLASH,
    ACTIONS(329), 1,
      aux_sym_string_token1,
    STATE(58), 1,
      aux_sym_string_repeat1,
  [1521] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(283), 1,
      anon_sym_SQUOTE,
    ACTIONS(331), 1,
      aux_sym_string_token3,
    STATE(59), 1,
      aux_sym_string_repeat2,
  [1537] = 5,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_BSLASH,
    ACTIONS(319), 1,
      anon_sym_BQUOTE,
    ACTIONS(349), 1,
      aux_sym_string_token4,
    STATE(66), 1,
      aux_sym_string_repeat3,
  [1553] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(306), 3,
      anon_sym_BSLASH,
      anon_sym_SQUOTE,
      aux_sym_string_token3,
  [1562] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(351), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1571] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(353), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1580] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(295), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [1589] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(355), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1598] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(314), 3,
      anon_sym_BSLASH,
      anon_sym_BQUOTE,
      aux_sym_string_token4,
  [1607] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 1,
      anon_sym_LBRACE,
    STATE(5), 1,
      sym__braced_code,
  [1617] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [1624] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
  [1631] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 1,
      anon_sym_RBRACE,
  [1638] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(365), 1,
      aux_sym_string_token2,
  [1645] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      ts_builtin_sym_end,
  [1652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_LBRACE,
  [1659] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(371), 1,
      aux_sym_string_token2,
  [1666] = 2,
    ACTIONS(247), 1,
      sym_comment,
    ACTIONS(373), 1,
      aux_sym_string_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 140,
  [SMALL_STATE(7)] = 174,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 228,
  [SMALL_STATE(10)] = 248,
  [SMALL_STATE(11)] = 268,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 308,
  [SMALL_STATE(14)] = 342,
  [SMALL_STATE(15)] = 362,
  [SMALL_STATE(16)] = 396,
  [SMALL_STATE(17)] = 416,
  [SMALL_STATE(18)] = 436,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 496,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 575,
  [SMALL_STATE(25)] = 600,
  [SMALL_STATE(26)] = 625,
  [SMALL_STATE(27)] = 650,
  [SMALL_STATE(28)] = 675,
  [SMALL_STATE(29)] = 700,
  [SMALL_STATE(30)] = 725,
  [SMALL_STATE(31)] = 750,
  [SMALL_STATE(32)] = 775,
  [SMALL_STATE(33)] = 800,
  [SMALL_STATE(34)] = 825,
  [SMALL_STATE(35)] = 850,
  [SMALL_STATE(36)] = 866,
  [SMALL_STATE(37)] = 882,
  [SMALL_STATE(38)] = 898,
  [SMALL_STATE(39)] = 914,
  [SMALL_STATE(40)] = 930,
  [SMALL_STATE(41)] = 952,
  [SMALL_STATE(42)] = 962,
  [SMALL_STATE(43)] = 972,
  [SMALL_STATE(44)] = 982,
  [SMALL_STATE(45)] = 992,
  [SMALL_STATE(46)] = 1002,
  [SMALL_STATE(47)] = 1012,
  [SMALL_STATE(48)] = 1022,
  [SMALL_STATE(49)] = 1032,
  [SMALL_STATE(50)] = 1049,
  [SMALL_STATE(51)] = 1066,
  [SMALL_STATE(52)] = 1085,
  [SMALL_STATE(53)] = 1104,
  [SMALL_STATE(54)] = 1121,
  [SMALL_STATE(55)] = 1137,
  [SMALL_STATE(56)] = 1153,
  [SMALL_STATE(57)] = 1169,
  [SMALL_STATE(58)] = 1185,
  [SMALL_STATE(59)] = 1201,
  [SMALL_STATE(60)] = 1217,
  [SMALL_STATE(61)] = 1233,
  [SMALL_STATE(62)] = 1249,
  [SMALL_STATE(63)] = 1265,
  [SMALL_STATE(64)] = 1281,
  [SMALL_STATE(65)] = 1297,
  [SMALL_STATE(66)] = 1313,
  [SMALL_STATE(67)] = 1329,
  [SMALL_STATE(68)] = 1345,
  [SMALL_STATE(69)] = 1361,
  [SMALL_STATE(70)] = 1377,
  [SMALL_STATE(71)] = 1393,
  [SMALL_STATE(72)] = 1409,
  [SMALL_STATE(73)] = 1425,
  [SMALL_STATE(74)] = 1441,
  [SMALL_STATE(75)] = 1457,
  [SMALL_STATE(76)] = 1473,
  [SMALL_STATE(77)] = 1489,
  [SMALL_STATE(78)] = 1505,
  [SMALL_STATE(79)] = 1521,
  [SMALL_STATE(80)] = 1537,
  [SMALL_STATE(81)] = 1553,
  [SMALL_STATE(82)] = 1562,
  [SMALL_STATE(83)] = 1571,
  [SMALL_STATE(84)] = 1580,
  [SMALL_STATE(85)] = 1589,
  [SMALL_STATE(86)] = 1598,
  [SMALL_STATE(87)] = 1607,
  [SMALL_STATE(88)] = 1617,
  [SMALL_STATE(89)] = 1624,
  [SMALL_STATE(90)] = 1631,
  [SMALL_STATE(91)] = 1638,
  [SMALL_STATE(92)] = 1645,
  [SMALL_STATE(93)] = 1652,
  [SMALL_STATE(94)] = 1659,
  [SMALL_STATE(95)] = 1666,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_block, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_block, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_code, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_code, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pre_operations_block, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post_operations_block, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__braced_code, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__braced_code, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 4, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 4, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pre_operations_block, 4, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [144] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [150] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post_operations_block, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [198] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [201] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [237] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0), SHIFT_REPEAT(49),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0),
  [262] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0), SHIFT_REPEAT(82),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_content, 1, 0, 1),
  [267] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [293] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [297] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [300] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [303] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(95),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [308] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(59),
  [311] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(91),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0),
  [316] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(60),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [327] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [337] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [339] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [341] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [343] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [345] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [347] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 1, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__js_braced, 2, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__js_braced, 3, 0, 0),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [365] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [367] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dataform(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dataform",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
