/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 51
#define ALIAS_COUNT 3
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_config = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  aux_sym__config_content_inner_token1 = 4,
  aux_sym__config_string_token1 = 5,
  aux_sym__config_string_token2 = 6,
  aux_sym__config_string_token3 = 7,
  anon_sym_js = 8,
  aux_sym__js_content_raw_token1 = 9,
  anon_sym_pre_operations = 10,
  anon_sym_post_operations = 11,
  sym_identifier = 12,
  sym_number = 13,
  sym_symbol = 14,
  anon_sym_DOLLAR_LBRACE = 15,
  aux_sym_interpolation_token1 = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_string_token1 = 18,
  anon_sym_BSLASH = 19,
  aux_sym_string_token2 = 20,
  anon_sym_SQUOTE = 21,
  aux_sym_string_token3 = 22,
  anon_sym_BQUOTE = 23,
  aux_sym_string_token4 = 24,
  sym_comment = 25,
  sym_source_file = 26,
  sym_config_block = 27,
  sym_config_content = 28,
  aux_sym__config_content_inner = 29,
  sym__config_braced = 30,
  sym__config_string = 31,
  sym_js_block = 32,
  sym_js_content = 33,
  aux_sym__js_content_raw = 34,
  sym__js_braced = 35,
  sym_pre_operations_block = 36,
  sym_post_operations_block = 37,
  sym_braced_code = 38,
  sym_statement = 39,
  sym_interpolation = 40,
  sym_string = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym__config_braced_repeat1 = 43,
  aux_sym__js_braced_repeat1 = 44,
  aux_sym_pre_operations_block_repeat1 = 45,
  aux_sym_braced_code_repeat1 = 46,
  aux_sym_interpolation_repeat1 = 47,
  aux_sym_string_repeat1 = 48,
  aux_sym_string_repeat2 = 49,
  aux_sym_string_repeat3 = 50,
  alias_sym_close_brace = 51,
  anon_alias_sym_js_content = 52,
  alias_sym_open_brace = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_config] = "config",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__config_content_inner_token1] = "_config_content_inner_token1",
  [aux_sym__config_string_token1] = "_config_string_token1",
  [aux_sym__config_string_token2] = "_config_string_token2",
  [aux_sym__config_string_token3] = "_config_string_token3",
  [anon_sym_js] = "js",
  [aux_sym__js_content_raw_token1] = "_js_content_raw_token1",
  [anon_sym_pre_operations] = "pre_operations",
  [anon_sym_post_operations] = "post_operations",
  [sym_identifier] = "identifier",
  [sym_number] = "number",
  [sym_symbol] = "symbol",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [aux_sym_interpolation_token1] = "interpolation_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token3] = "string_token3",
  [anon_sym_BQUOTE] = "`",
  [aux_sym_string_token4] = "string_token4",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_config_block] = "config_block",
  [sym_config_content] = "config_content",
  [aux_sym__config_content_inner] = "_config_content_inner",
  [sym__config_braced] = "_config_braced",
  [sym__config_string] = "_config_string",
  [sym_js_block] = "js_block",
  [sym_js_content] = "js_content",
  [aux_sym__js_content_raw] = "_js_content_raw",
  [sym__js_braced] = "_js_braced",
  [sym_pre_operations_block] = "pre_operations_block",
  [sym_post_operations_block] = "post_operations_block",
  [sym_braced_code] = "braced_code",
  [sym_statement] = "statement",
  [sym_interpolation] = "interpolation",
  [sym_string] = "string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__config_braced_repeat1] = "_config_braced_repeat1",
  [aux_sym__js_braced_repeat1] = "_js_braced_repeat1",
  [aux_sym_pre_operations_block_repeat1] = "pre_operations_block_repeat1",
  [aux_sym_braced_code_repeat1] = "braced_code_repeat1",
  [aux_sym_interpolation_repeat1] = "interpolation_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_string_repeat3] = "string_repeat3",
  [alias_sym_close_brace] = "close_brace",
  [anon_alias_sym_js_content] = "js_content",
  [alias_sym_open_brace] = "open_brace",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_config] = anon_sym_config,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__config_content_inner_token1] = aux_sym__config_content_inner_token1,
  [aux_sym__config_string_token1] = aux_sym__config_string_token1,
  [aux_sym__config_string_token2] = aux_sym__config_string_token2,
  [aux_sym__config_string_token3] = aux_sym__config_string_token3,
  [anon_sym_js] = anon_sym_js,
  [aux_sym__js_content_raw_token1] = aux_sym__js_content_raw_token1,
  [anon_sym_pre_operations] = anon_sym_pre_operations,
  [anon_sym_post_operations] = anon_sym_post_operations,
  [sym_identifier] = sym_identifier,
  [sym_number] = sym_number,
  [sym_symbol] = sym_symbol,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [aux_sym_interpolation_token1] = aux_sym_interpolation_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token3] = aux_sym_string_token3,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [aux_sym_string_token4] = aux_sym_string_token4,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_config_block] = sym_config_block,
  [sym_config_content] = sym_config_content,
  [aux_sym__config_content_inner] = aux_sym__config_content_inner,
  [sym__config_braced] = sym__config_braced,
  [sym__config_string] = sym__config_string,
  [sym_js_block] = sym_js_block,
  [sym_js_content] = sym_js_content,
  [aux_sym__js_content_raw] = aux_sym__js_content_raw,
  [sym__js_braced] = sym__js_braced,
  [sym_pre_operations_block] = sym_pre_operations_block,
  [sym_post_operations_block] = sym_post_operations_block,
  [sym_braced_code] = sym_braced_code,
  [sym_statement] = sym_statement,
  [sym_interpolation] = sym_interpolation,
  [sym_string] = sym_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__config_braced_repeat1] = aux_sym__config_braced_repeat1,
  [aux_sym__js_braced_repeat1] = aux_sym__js_braced_repeat1,
  [aux_sym_pre_operations_block_repeat1] = aux_sym_pre_operations_block_repeat1,
  [aux_sym_braced_code_repeat1] = aux_sym_braced_code_repeat1,
  [aux_sym_interpolation_repeat1] = aux_sym_interpolation_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_string_repeat3] = aux_sym_string_repeat3,
  [alias_sym_close_brace] = alias_sym_close_brace,
  [anon_alias_sym_js_content] = anon_alias_sym_js_content,
  [alias_sym_open_brace] = alias_sym_open_brace,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_config] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__config_content_inner_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__config_string_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__config_string_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__config_string_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_js] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__js_content_raw_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_pre_operations] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_post_operations] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpolation_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token3] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_config_block] = {
    .visible = true,
    .named = true,
  },
  [sym_config_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__config_content_inner] = {
    .visible = false,
    .named = false,
  },
  [sym__config_braced] = {
    .visible = false,
    .named = true,
  },
  [sym__config_string] = {
    .visible = false,
    .named = true,
  },
  [sym_js_block] = {
    .visible = true,
    .named = true,
  },
  [sym_js_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__js_content_raw] = {
    .visible = false,
    .named = false,
  },
  [sym__js_braced] = {
    .visible = false,
    .named = true,
  },
  [sym_pre_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_post_operations_block] = {
    .visible = true,
    .named = true,
  },
  [sym_braced_code] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__config_braced_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__js_braced_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pre_operations_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat3] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_close_brace] = {
    .visible = true,
    .named = true,
  },
  [anon_alias_sym_js_content] = {
    .visible = true,
    .named = false,
  },
  [alias_sym_open_brace] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_open_brace,
    [1] = alias_sym_close_brace,
  },
  [2] = {
    [1] = alias_sym_open_brace,
    [2] = alias_sym_close_brace,
  },
  [3] = {
    [0] = anon_alias_sym_js_content,
  },
  [4] = {
    [0] = alias_sym_open_brace,
    [2] = alias_sym_close_brace,
  },
  [5] = {
    [1] = alias_sym_open_brace,
    [3] = alias_sym_close_brace,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__js_content_raw, 2,
    aux_sym__js_content_raw,
    anon_alias_sym_js_content,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 24,
  [36] = 29,
  [37] = 25,
  [38] = 31,
  [39] = 14,
  [40] = 7,
  [41] = 15,
  [42] = 22,
  [43] = 8,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 47,
  [48] = 48,
  [49] = 15,
  [50] = 50,
  [51] = 50,
  [52] = 8,
  [53] = 8,
  [54] = 15,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 64,
  [69] = 60,
  [70] = 70,
  [71] = 70,
  [72] = 67,
  [73] = 63,
  [74] = 61,
  [75] = 64,
  [76] = 60,
  [77] = 70,
  [78] = 67,
  [79] = 63,
  [80] = 61,
  [81] = 64,
  [82] = 60,
  [83] = 70,
  [84] = 67,
  [85] = 63,
  [86] = 61,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '"', 90,
        '$', 15,
        '\'', 100,
        '-', 81,
        '/', 80,
        '\\', 95,
        '`', 105,
        'c', 59,
        'j', 69,
        'p', 61,
        '{', 22,
        '}', 23,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead == '!' ||
          ('(' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '>') ||
          ('[' <= lookahead && lookahead <= ']')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '-') ADVANCE(98);
      if (lookahead == '/') ADVANCE(97);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0) ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '$') ADVANCE(15);
      if (lookahead == '\'') ADVANCE(100);
      if (lookahead == '-') ADVANCE(81);
      if (lookahead == '/') ADVANCE(80);
      if (lookahead == '`') ADVANCE(105);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead == '!' ||
          ('(' <= lookahead && lookahead <= '.') ||
          (';' <= lookahead && lookahead <= '>') ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '\'') ADVANCE(100);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '`') ADVANCE(105);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '\'') ADVANCE(100);
      if (lookahead == '-') ADVANCE(88);
      if (lookahead == '/') ADVANCE(84);
      if (lookahead == '`') ADVANCE(105);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(90);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead == '/') ADVANCE(92);
      if (lookahead == '\\') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(25);
      if (lookahead == '`') ADVANCE(14);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '\'') ADVANCE(100);
      if (lookahead == '-') ADVANCE(103);
      if (lookahead == '/') ADVANCE(102);
      if (lookahead == '\\') ADVANCE(95);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0) ADVANCE(101);
      END_STATE();
    case 9:
      if (lookahead == '\'') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead == '/') ADVANCE(110);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 11:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '/') ADVANCE(36);
      if (lookahead == '{') ADVANCE(22);
      if (lookahead == '}') ADVANCE(23);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 13:
      if (lookahead == '-') ADVANCE(108);
      if (lookahead == '/') ADVANCE(107);
      if (lookahead == '\\') ADVANCE(95);
      if (lookahead == '`') ADVANCE(105);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(109);
      if (lookahead != 0) ADVANCE(106);
      END_STATE();
    case 14:
      if (lookahead == '\\') ADVANCE(19);
      if (lookahead == '`') ADVANCE(33);
      if (lookahead != 0) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '{') ADVANCE(82);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_config);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(111);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '*') ADVANCE(26);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '/') ADVANCE(25);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead == '-') ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__config_content_inner_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__config_string_token1);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__config_string_token2);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym__config_string_token3);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_js);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(111);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(38);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '*') ADVANCE(37);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '/') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__js_content_raw_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_pre_operations);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_post_operations);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(70);
      if (lookahead == 'r') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_symbol);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(111);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '\n') ADVANCE(89);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(111);
      if (lookahead != 0) ADVANCE(83);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(86);
      if (lookahead == '/') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '/') ADVANCE(89);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '*') ADVANCE(85);
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '`' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(11);
      if (lookahead != 0) ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '-') ADVANCE(88);
      if (lookahead == '/') ADVANCE(84);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_interpolation_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(111);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead == '/') ADVANCE(92);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(91);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(111);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '-') ADVANCE(98);
      if (lookahead == '/') ADVANCE(97);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(96);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_string_token3);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(111);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_string_token3);
      if (lookahead == '-') ADVANCE(103);
      if (lookahead == '/') ADVANCE(102);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(101);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(aux_sym_string_token4);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(111);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '-') ADVANCE(111);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_string_token4);
      if (lookahead == '-') ADVANCE(108);
      if (lookahead == '/') ADVANCE(107);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\\' &&
          lookahead != '`') ADVANCE(106);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(111);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 12},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 12},
  [56] = {.lex_state = 12},
  [57] = {.lex_state = 12},
  [58] = {.lex_state = 12},
  [59] = {.lex_state = 12},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 5},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 13},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 5},
  [72] = {.lex_state = 8},
  [73] = {.lex_state = 13},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 8},
  [76] = {.lex_state = 13},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 8},
  [79] = {.lex_state = 13},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 8},
  [82] = {.lex_state = 13},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 8},
  [85] = {.lex_state = 13},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 12},
  [89] = {.lex_state = 12},
  [90] = {.lex_state = 8},
  [91] = {.lex_state = 13},
  [92] = {.lex_state = 12},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_config] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_js] = ACTIONS(1),
    [anon_sym_pre_operations] = ACTIONS(1),
    [anon_sym_post_operations] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(96),
    [sym_config_block] = STATE(2),
    [sym_js_block] = STATE(2),
    [sym_pre_operations_block] = STATE(2),
    [sym_post_operations_block] = STATE(2),
    [sym_statement] = STATE(2),
    [sym_interpolation] = STATE(22),
    [sym_string] = STATE(22),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_config] = ACTIONS(7),
    [anon_sym_js] = ACTIONS(9),
    [anon_sym_pre_operations] = ACTIONS(11),
    [anon_sym_post_operations] = ACTIONS(13),
    [sym_identifier] = ACTIONS(15),
    [sym_number] = ACTIONS(17),
    [sym_symbol] = ACTIONS(15),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_config,
    ACTIONS(9), 1,
      anon_sym_js,
    ACTIONS(11), 1,
      anon_sym_pre_operations,
    ACTIONS(13), 1,
      anon_sym_post_operations,
    ACTIONS(17), 1,
      sym_number,
    ACTIONS(19), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      anon_sym_SQUOTE,
    ACTIONS(25), 1,
      anon_sym_BQUOTE,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 2,
      sym_identifier,
      sym_symbol,
    STATE(22), 2,
      sym_interpolation,
      sym_string,
    STATE(3), 6,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_statement,
      aux_sym_source_file_repeat1,
  [50] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_config,
    ACTIONS(34), 1,
      anon_sym_js,
    ACTIONS(37), 1,
      anon_sym_pre_operations,
    ACTIONS(40), 1,
      anon_sym_post_operations,
    ACTIONS(46), 1,
      sym_number,
    ACTIONS(49), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(52), 1,
      anon_sym_DQUOTE,
    ACTIONS(55), 1,
      anon_sym_SQUOTE,
    ACTIONS(58), 1,
      anon_sym_BQUOTE,
    ACTIONS(43), 2,
      sym_identifier,
      sym_symbol,
    STATE(22), 2,
      sym_interpolation,
      sym_string,
    STATE(3), 6,
      sym_config_block,
      sym_js_block,
      sym_pre_operations_block,
      sym_post_operations_block,
      sym_statement,
      aux_sym_source_file_repeat1,
  [100] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      sym_symbol,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_SQUOTE,
    ACTIONS(73), 1,
      anon_sym_BQUOTE,
    ACTIONS(63), 2,
      sym_identifier,
      sym_number,
    STATE(20), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(42), 2,
      sym_interpolation,
      sym_string,
  [134] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_symbol,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_SQUOTE,
    ACTIONS(73), 1,
      anon_sym_BQUOTE,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 2,
      sym_identifier,
      sym_number,
    STATE(12), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(42), 2,
      sym_interpolation,
      sym_string,
  [168] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_symbol,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_SQUOTE,
    ACTIONS(73), 1,
      anon_sym_BQUOTE,
    ACTIONS(77), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 2,
      sym_identifier,
      sym_number,
    STATE(4), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(42), 2,
      sym_interpolation,
      sym_string,
  [202] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(81), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(85), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [242] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(89), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [262] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(93), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [282] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(97), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [302] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      sym_symbol,
    ACTIONS(67), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    ACTIONS(71), 1,
      anon_sym_SQUOTE,
    ACTIONS(73), 1,
      anon_sym_BQUOTE,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(63), 2,
      sym_identifier,
      sym_number,
    STATE(20), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(42), 2,
      sym_interpolation,
      sym_string,
  [336] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(103), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [356] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(107), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [376] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(111), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [396] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(115), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [416] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(119), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [436] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(123), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(127), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [476] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(134), 1,
      sym_symbol,
    ACTIONS(137), 1,
      anon_sym_DOLLAR_LBRACE,
    ACTIONS(140), 1,
      anon_sym_DQUOTE,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
    ACTIONS(146), 1,
      anon_sym_BQUOTE,
    ACTIONS(131), 2,
      sym_identifier,
      sym_number,
    STATE(20), 2,
      sym_statement,
      aux_sym_pre_operations_block_repeat1,
    STATE(42), 2,
      sym_interpolation,
      sym_string,
  [510] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(151), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [530] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 6,
      ts_builtin_sym_end,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
    ACTIONS(155), 6,
      anon_sym_config,
      anon_sym_js,
      anon_sym_pre_operations,
      anon_sym_post_operations,
      sym_identifier,
      sym_symbol,
  [550] = 7,
    ACTIONS(157), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
    ACTIONS(165), 1,
      anon_sym_DQUOTE,
    ACTIONS(168), 1,
      anon_sym_SQUOTE,
    ACTIONS(171), 1,
      anon_sym_BQUOTE,
    ACTIONS(162), 2,
      aux_sym__config_content_inner_token1,
      sym_comment,
    STATE(23), 3,
      sym_braced_code,
      sym_string,
      aux_sym_braced_code_repeat1,
  [575] = 7,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    ACTIONS(178), 2,
      aux_sym__config_content_inner_token1,
      sym_comment,
    STATE(31), 3,
      sym_braced_code,
      sym_string,
      aux_sym_braced_code_repeat1,
  [600] = 7,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_BQUOTE,
    ACTIONS(190), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(29), 3,
      sym_braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [625] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_RBRACE,
    ACTIONS(204), 1,
      sym_comment,
    STATE(34), 3,
      sym__config_braced,
      sym__config_string,
      aux_sym__config_braced_repeat1,
    ACTIONS(202), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [646] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(26), 3,
      sym__config_braced,
      sym__config_string,
      aux_sym__config_braced_repeat1,
    ACTIONS(208), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [667] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LBRACE,
    ACTIONS(213), 1,
      anon_sym_RBRACE,
    STATE(28), 3,
      aux_sym__config_content_inner,
      sym__config_braced,
      sym__config_string,
    ACTIONS(215), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [688] = 7,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_BQUOTE,
    ACTIONS(218), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(33), 3,
      sym_braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [713] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
    STATE(32), 3,
      aux_sym__config_content_inner,
      sym__config_braced,
      sym__config_string,
    ACTIONS(224), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [734] = 7,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    ACTIONS(228), 2,
      aux_sym__config_content_inner_token1,
      sym_comment,
    STATE(23), 3,
      sym_braced_code,
      sym_string,
      aux_sym_braced_code_repeat1,
  [759] = 5,
    ACTIONS(198), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(28), 3,
      aux_sym__config_content_inner,
      sym__config_braced,
      sym__config_string,
    ACTIONS(232), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [780] = 7,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    ACTIONS(237), 1,
      anon_sym_RBRACE,
    ACTIONS(242), 1,
      anon_sym_DQUOTE,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    ACTIONS(248), 1,
      anon_sym_BQUOTE,
    ACTIONS(239), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(33), 3,
      sym_braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [805] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_LBRACE,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(34), 3,
      sym__config_braced,
      sym__config_string,
      aux_sym__config_braced_repeat1,
    ACTIONS(256), 4,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [826] = 7,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    ACTIONS(259), 1,
      anon_sym_RBRACE,
    ACTIONS(261), 2,
      aux_sym__config_content_inner_token1,
      sym_comment,
    STATE(38), 3,
      sym_braced_code,
      sym_string,
      aux_sym_braced_code_repeat1,
  [851] = 7,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_BQUOTE,
    ACTIONS(263), 1,
      anon_sym_RBRACE,
    ACTIONS(220), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(33), 3,
      sym_braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [876] = 7,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 1,
      anon_sym_DQUOTE,
    ACTIONS(194), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      anon_sym_BQUOTE,
    ACTIONS(265), 1,
      anon_sym_RBRACE,
    ACTIONS(267), 2,
      aux_sym_interpolation_token1,
      sym_comment,
    STATE(36), 3,
      sym_braced_code,
      sym_string,
      aux_sym_interpolation_repeat1,
  [901] = 7,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    ACTIONS(180), 1,
      anon_sym_DQUOTE,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
    ACTIONS(184), 1,
      anon_sym_BQUOTE,
    ACTIONS(269), 1,
      anon_sym_RBRACE,
    ACTIONS(228), 2,
      aux_sym__config_content_inner_token1,
      sym_comment,
    STATE(23), 3,
      sym_braced_code,
      sym_string,
      aux_sym_braced_code_repeat1,
  [926] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      sym_symbol,
    ACTIONS(105), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [942] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      sym_symbol,
    ACTIONS(79), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      sym_symbol,
    ACTIONS(109), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [974] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_symbol,
    ACTIONS(153), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [990] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_symbol,
    ACTIONS(83), 7,
      anon_sym_RBRACE,
      sym_identifier,
      sym_number,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [1006] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(271), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [1018] = 1,
    ACTIONS(273), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1028] = 1,
    ACTIONS(273), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1038] = 7,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(277), 1,
      anon_sym_RBRACE,
    ACTIONS(279), 1,
      aux_sym__js_content_raw_token1,
    STATE(58), 1,
      aux_sym__js_content_raw,
    STATE(89), 1,
      sym__js_braced,
    STATE(95), 1,
      sym_js_content,
  [1060] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(281), 6,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      aux_sym__config_string_token1,
      aux_sym__config_string_token2,
      aux_sym__config_string_token3,
  [1072] = 1,
    ACTIONS(111), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1082] = 1,
    ACTIONS(283), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1092] = 1,
    ACTIONS(283), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1102] = 1,
    ACTIONS(85), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym_interpolation_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1112] = 1,
    ACTIONS(85), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1122] = 1,
    ACTIONS(111), 7,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__config_content_inner_token1,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_comment,
  [1132] = 6,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
    ACTIONS(290), 1,
      aux_sym__js_content_raw_token1,
    STATE(55), 1,
      aux_sym__js_content_raw,
    STATE(89), 1,
      sym__js_braced,
  [1151] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LBRACE,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    ACTIONS(298), 1,
      aux_sym__js_content_raw_token1,
    STATE(56), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1168] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    ACTIONS(303), 1,
      aux_sym__js_content_raw_token1,
    STATE(56), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1185] = 6,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(279), 1,
      aux_sym__js_content_raw_token1,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(55), 1,
      aux_sym__js_content_raw,
    STATE(89), 1,
      sym__js_braced,
  [1204] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
    ACTIONS(307), 1,
      anon_sym_RBRACE,
    ACTIONS(309), 1,
      aux_sym__js_content_raw_token1,
    STATE(57), 2,
      sym__js_braced,
      aux_sym__js_braced_repeat1,
  [1221] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(313), 1,
      anon_sym_BQUOTE,
    ACTIONS(315), 1,
      aux_sym_string_token4,
    STATE(63), 1,
      aux_sym_string_repeat3,
  [1237] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_DQUOTE,
    ACTIONS(317), 1,
      aux_sym_string_token1,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    STATE(70), 1,
      aux_sym_string_repeat1,
  [1253] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_BSLASH,
    ACTIONS(324), 1,
      anon_sym_BQUOTE,
    ACTIONS(326), 1,
      aux_sym_string_token4,
    STATE(62), 1,
      aux_sym_string_repeat3,
  [1269] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(329), 1,
      anon_sym_BQUOTE,
    ACTIONS(331), 1,
      aux_sym_string_token4,
    STATE(62), 1,
      aux_sym_string_repeat3,
  [1285] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_SQUOTE,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(335), 1,
      aux_sym_string_token3,
    STATE(67), 1,
      aux_sym_string_repeat2,
  [1301] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(337), 1,
      anon_sym_DQUOTE,
    ACTIONS(339), 1,
      aux_sym_string_token1,
    ACTIONS(342), 1,
      anon_sym_BSLASH,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1317] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(345), 1,
      anon_sym_BSLASH,
    ACTIONS(348), 1,
      anon_sym_SQUOTE,
    ACTIONS(350), 1,
      aux_sym_string_token3,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [1333] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(329), 1,
      anon_sym_SQUOTE,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(353), 1,
      aux_sym_string_token3,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [1349] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(355), 1,
      anon_sym_SQUOTE,
    ACTIONS(357), 1,
      aux_sym_string_token3,
    STATE(72), 1,
      aux_sym_string_repeat2,
  [1365] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(355), 1,
      anon_sym_BQUOTE,
    ACTIONS(359), 1,
      aux_sym_string_token4,
    STATE(73), 1,
      aux_sym_string_repeat3,
  [1381] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(329), 1,
      anon_sym_DQUOTE,
    ACTIONS(361), 1,
      aux_sym_string_token1,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1397] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(361), 1,
      aux_sym_string_token1,
    ACTIONS(363), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1413] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(353), 1,
      aux_sym_string_token3,
    ACTIONS(363), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [1429] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(331), 1,
      aux_sym_string_token4,
    ACTIONS(363), 1,
      anon_sym_BQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat3,
  [1445] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(365), 1,
      anon_sym_DQUOTE,
    ACTIONS(367), 1,
      aux_sym_string_token1,
    STATE(77), 1,
      aux_sym_string_repeat1,
  [1461] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(365), 1,
      anon_sym_SQUOTE,
    ACTIONS(369), 1,
      aux_sym_string_token3,
    STATE(78), 1,
      aux_sym_string_repeat2,
  [1477] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(365), 1,
      anon_sym_BQUOTE,
    ACTIONS(371), 1,
      aux_sym_string_token4,
    STATE(79), 1,
      aux_sym_string_repeat3,
  [1493] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(361), 1,
      aux_sym_string_token1,
    ACTIONS(373), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1509] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(353), 1,
      aux_sym_string_token3,
    ACTIONS(373), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [1525] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(331), 1,
      aux_sym_string_token4,
    ACTIONS(373), 1,
      anon_sym_BQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat3,
  [1541] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(375), 1,
      anon_sym_DQUOTE,
    ACTIONS(377), 1,
      aux_sym_string_token1,
    STATE(83), 1,
      aux_sym_string_repeat1,
  [1557] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(375), 1,
      anon_sym_SQUOTE,
    ACTIONS(379), 1,
      aux_sym_string_token3,
    STATE(84), 1,
      aux_sym_string_repeat2,
  [1573] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(375), 1,
      anon_sym_BQUOTE,
    ACTIONS(381), 1,
      aux_sym_string_token4,
    STATE(85), 1,
      aux_sym_string_repeat3,
  [1589] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(361), 1,
      aux_sym_string_token1,
    ACTIONS(383), 1,
      anon_sym_DQUOTE,
    STATE(65), 1,
      aux_sym_string_repeat1,
  [1605] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_BSLASH,
    ACTIONS(353), 1,
      aux_sym_string_token3,
    ACTIONS(383), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat2,
  [1621] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(311), 1,
      anon_sym_BSLASH,
    ACTIONS(331), 1,
      aux_sym_string_token4,
    ACTIONS(383), 1,
      anon_sym_BQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat3,
  [1637] = 5,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_BSLASH,
    ACTIONS(355), 1,
      anon_sym_DQUOTE,
    ACTIONS(385), 1,
      aux_sym_string_token1,
    STATE(71), 1,
      aux_sym_string_repeat1,
  [1653] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(337), 3,
      anon_sym_DQUOTE,
      aux_sym_string_token1,
      anon_sym_BSLASH,
  [1662] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(387), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1671] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(389), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1680] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(348), 3,
      anon_sym_BSLASH,
      anon_sym_SQUOTE,
      aux_sym_string_token3,
  [1689] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(324), 3,
      anon_sym_BSLASH,
      anon_sym_BQUOTE,
      aux_sym_string_token4,
  [1698] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(391), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      aux_sym__js_content_raw_token1,
  [1707] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(393), 1,
      anon_sym_LBRACE,
    STATE(16), 1,
      sym_config_content,
  [1717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(395), 1,
      anon_sym_LBRACE,
  [1724] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(397), 1,
      anon_sym_RBRACE,
  [1731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(399), 1,
      ts_builtin_sym_end,
  [1738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(401), 1,
      anon_sym_LBRACE,
  [1745] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(403), 1,
      aux_sym_string_token2,
  [1752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(405), 1,
      anon_sym_LBRACE,
  [1759] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(407), 1,
      aux_sym_string_token2,
  [1766] = 2,
    ACTIONS(204), 1,
      sym_comment,
    ACTIONS(409), 1,
      aux_sym_string_token2,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 134,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 202,
  [SMALL_STATE(8)] = 222,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 282,
  [SMALL_STATE(12)] = 302,
  [SMALL_STATE(13)] = 336,
  [SMALL_STATE(14)] = 356,
  [SMALL_STATE(15)] = 376,
  [SMALL_STATE(16)] = 396,
  [SMALL_STATE(17)] = 416,
  [SMALL_STATE(18)] = 436,
  [SMALL_STATE(19)] = 456,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 510,
  [SMALL_STATE(22)] = 530,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 575,
  [SMALL_STATE(25)] = 600,
  [SMALL_STATE(26)] = 625,
  [SMALL_STATE(27)] = 646,
  [SMALL_STATE(28)] = 667,
  [SMALL_STATE(29)] = 688,
  [SMALL_STATE(30)] = 713,
  [SMALL_STATE(31)] = 734,
  [SMALL_STATE(32)] = 759,
  [SMALL_STATE(33)] = 780,
  [SMALL_STATE(34)] = 805,
  [SMALL_STATE(35)] = 826,
  [SMALL_STATE(36)] = 851,
  [SMALL_STATE(37)] = 876,
  [SMALL_STATE(38)] = 901,
  [SMALL_STATE(39)] = 926,
  [SMALL_STATE(40)] = 942,
  [SMALL_STATE(41)] = 958,
  [SMALL_STATE(42)] = 974,
  [SMALL_STATE(43)] = 990,
  [SMALL_STATE(44)] = 1006,
  [SMALL_STATE(45)] = 1018,
  [SMALL_STATE(46)] = 1028,
  [SMALL_STATE(47)] = 1038,
  [SMALL_STATE(48)] = 1060,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1082,
  [SMALL_STATE(51)] = 1092,
  [SMALL_STATE(52)] = 1102,
  [SMALL_STATE(53)] = 1112,
  [SMALL_STATE(54)] = 1122,
  [SMALL_STATE(55)] = 1132,
  [SMALL_STATE(56)] = 1151,
  [SMALL_STATE(57)] = 1168,
  [SMALL_STATE(58)] = 1185,
  [SMALL_STATE(59)] = 1204,
  [SMALL_STATE(60)] = 1221,
  [SMALL_STATE(61)] = 1237,
  [SMALL_STATE(62)] = 1253,
  [SMALL_STATE(63)] = 1269,
  [SMALL_STATE(64)] = 1285,
  [SMALL_STATE(65)] = 1301,
  [SMALL_STATE(66)] = 1317,
  [SMALL_STATE(67)] = 1333,
  [SMALL_STATE(68)] = 1349,
  [SMALL_STATE(69)] = 1365,
  [SMALL_STATE(70)] = 1381,
  [SMALL_STATE(71)] = 1397,
  [SMALL_STATE(72)] = 1413,
  [SMALL_STATE(73)] = 1429,
  [SMALL_STATE(74)] = 1445,
  [SMALL_STATE(75)] = 1461,
  [SMALL_STATE(76)] = 1477,
  [SMALL_STATE(77)] = 1493,
  [SMALL_STATE(78)] = 1509,
  [SMALL_STATE(79)] = 1525,
  [SMALL_STATE(80)] = 1541,
  [SMALL_STATE(81)] = 1557,
  [SMALL_STATE(82)] = 1573,
  [SMALL_STATE(83)] = 1589,
  [SMALL_STATE(84)] = 1605,
  [SMALL_STATE(85)] = 1621,
  [SMALL_STATE(86)] = 1637,
  [SMALL_STATE(87)] = 1653,
  [SMALL_STATE(88)] = 1662,
  [SMALL_STATE(89)] = 1671,
  [SMALL_STATE(90)] = 1680,
  [SMALL_STATE(91)] = 1689,
  [SMALL_STATE(92)] = 1698,
  [SMALL_STATE(93)] = 1707,
  [SMALL_STATE(94)] = 1717,
  [SMALL_STATE(95)] = 1724,
  [SMALL_STATE(96)] = 1731,
  [SMALL_STATE(97)] = 1738,
  [SMALL_STATE(98)] = 1745,
  [SMALL_STATE(99)] = 1752,
  [SMALL_STATE(100)] = 1759,
  [SMALL_STATE(101)] = 1766,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(93),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(97),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_content, 2, 0, 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_content, 2, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 3, 0, 2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 3, 0, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 3, 0, 2),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pre_operations_block, 3, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 3, 0, 2),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post_operations_block, 3, 0, 2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_block, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_block, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_config_content, 3, 0, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_config_content, 3, 0, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_js_block, 4, 0, 5),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_block, 4, 0, 5),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pre_operations_block, 4, 0, 5),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pre_operations_block, 4, 0, 5),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pre_operations_block_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_post_operations_block, 4, 0, 5),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_post_operations_block, 4, 0, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [157] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_code_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [190] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__config_content_inner, 2, 0, 0), SHIFT_REPEAT(27),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__config_content_inner, 2, 0, 0),
  [215] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__config_content_inner, 2, 0, 0), SHIFT_REPEAT(28),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0),
  [239] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [242] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [245] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [248] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [251] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__config_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [254] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__config_braced_repeat1, 2, 0, 0),
  [256] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__config_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [261] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__config_braced, 2, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_code, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__config_braced, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_code, 3, 0, 0),
  [285] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0), SHIFT_REPEAT(59),
  [288] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0),
  [290] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 2, 0, 0), SHIFT_REPEAT(89),
  [293] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [296] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0),
  [298] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__js_braced_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_js_content, 1, 0, 3),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [311] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [315] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [317] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [319] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [321] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(100),
  [324] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0),
  [326] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(62),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [331] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [333] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [339] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [342] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [345] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(98),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [350] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(66),
  [353] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [355] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [357] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [359] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [361] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [363] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [365] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [377] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [381] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [383] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [385] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [387] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__js_braced, 3, 0, 0),
  [389] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__js_content_raw, 1, 0, 0),
  [391] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__js_braced, 2, 0, 0),
  [393] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [395] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [397] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [399] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [403] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [407] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [409] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dataform(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dataform",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
